// Package openapi3 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.9.0 DO NOT EDIT.
package openapi3

// Data defines model for Data.
type Data struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// CreateStoreDataResponse defines model for CreateStoreDataResponse.
type CreateStoreDataResponse struct {
	Data *Data `json:"data,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error *string `json:"error,omitempty"`
}

// SaveStoreDataRequest defines model for SaveStoreDataRequest.
type SaveStoreDataRequest struct {
	Key   *string `json:"key,omitempty"`
	Value *string `json:"value,omitempty"`
}

// SaveDataJSONRequestBody defines body for SaveData for application/json ContentType.
type SaveDataJSONRequestBody SaveStoreDataRequest
